version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://18.217.112.15:5433/filmesdb
      SPRING_DATASOURCE_USERNAME: filmes_user
      SPRING_DATASOURCE_PASSWORD: filmes_password
      FASTAPI_URL: http://fastapi:8000
    ports:
      - "8080:8080"
    depends_on:
      - fastapi
    networks:
      - app_network

  fastapi:
    build:
      context: ../app
      dockerfile: Dockerfile
    container_name: fastapi_service
    ports:
      - "8000:8000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
